# Generated by Django 5.2.1 on 2025-05-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=40)),
                ('door_num', models.IntegerField()),
                ('transmission', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default='AUTO', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=999)),
            ],
        ),
    ]
